server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

spring:
  application:
    name: notification-service

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.common.model
        spring.json.value.default.type: com.example.common.model.UserEvent
      enable-auto-commit: true

  mail:
    host: smtp.example.com
    port: 587
    username: your-email@mail.com
    password: your-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8


