server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NadezhdaTA/aston-config-repo.git
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
