server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true

      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notification/**

